In [2]:
import numpy as np

# Q1. Create a Python list representing vector v = [2, -1, 3] and multiply it by scalar 4.

In [3]:
v = [2, -1, 3]
sc =  4
v * sc

[2, -1, 3, 2, -1, 3, 2, -1, 3, 2, -1, 3]

It will repeat (duplicate) our list 4 times, not perform multiplication as in linear algebra.
To achieve true vector multiplication, we need to create our vector using the numpy library.

In [4]:
v_ = np.array([2, -1, 3])
v_ * sc

array([ 8, -4, 12])

# Q2. Given vector a = [5, -3] and scalar $\lambda$ = -2

In [5]:
a = np.array([5, -3])
lam = -2

lambda_a = lam * a

mag_a = np.linalg.norm(a)
mag_lambda_a = np.linalg.norm(lambda_a)

print("λa =", lambda_a)
print("|a| =", mag_a)
print("|λa| =", mag_lambda_a)

print("Ratio |λa| / |a| =", mag_lambda_a / mag_a)

λa = [-10   6]
|a| = 5.830951894845301
|λa| = 11.661903789690601
Ratio |λa| / |a| = 2.0


# Q3. Create:
Column vector shape (3,1)

Row vector shape (1,4)

Print the shape of the results

Add them using NumPy broadcasting.


In [14]:
c = np.array([[1], [2], [3]])
r = np.array([[1, 2, 3, 4]])
print(c.shape)
print(r.shape)

br = c + r
print(br)

(3, 1)
(1, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


# Q4 . Create vector v = [1,2,3,4] and add scalar 5.
Explain why NumPy allows this.

In [19]:
v = np.array([[1,2,3,4]])
sc = 5
v + sc

array([[6, 7, 8, 9]])

NumPy allows this because of broadcasting. The scalar 5 is automatically expanded to match the shape of the vector [1, 2, 3, 4], so it behaves like [5, 5, 5, 5] and gets added element-wise.

# Q5. Given vector a = [1,2,3,4,5,6], compute its
Euclidean norm manually and using NumPy.
Hint: By "manually," I mean solving it step by step using only basic NumPy functions.

In [24]:
a = np.array([[1,2,3,4,5,6]])

a_ = a ** 2
sum_ = np.sum(a_)
sqrt_ = np.sqrt(sum_)
print(sqrt_)

np_norm = np.linalg.norm(a)
print(np_norm)

9.539392014169456
9.539392014169456


# Q6. Generate a random vector of length 10 and normalize it. Print the norm before and after normalization

In [28]:
v = np.random.rand(10)
print(v)
norm_b = np.linalg.norm(v)
print(norm_b)
v_n = v / norm_b
print(v_n)
norm_a = np.linalg.norm(v_n)
print(norm_a)

[0.09905324 0.61181502 0.95555602 0.59129024 0.11226892 0.3192661
 0.20529362 0.98664337 0.19433125 0.09113376]
1.6801953351379482
[0.05895341 0.36413327 0.56871722 0.35191756 0.06681897 0.19001725
 0.12218438 0.58721944 0.11565991 0.05423998]
0.9999999999999999


# Q7. Compute the dot product of vectors
a = [1,2,3,4,5,6] & b = [0,-4,3,-3,6,5]
1. Manual loop
2. NumPy np.dot() .

In [33]:
#1
a = np.array([1,2,3,4,5,6])
b = np.array([0,-4,3,-3,6,5])

dotp_manual = 0;
for i in range(len(a)):
    dotp_manual += a[i] * b[i];

print(dotp_manual)

dotp = np.dot(a, b)
print(dotp)

49
49


# Q8. Verify the distributive property:
$$a · (b + c) = a · b + a · c$$
Hint: Generate three random numbers

In [56]:
a = np.random.rand(1)
b = np.random.rand(1)
c = np.random.rand(1)
lside = np.dot(a, b+c)
rside = np.dot(a, b) + np.dot(a, c)
print(lside == rside)

True


# Q9: Compute the Euclidean distance matrix between every point in group A and every point in group B.

In [65]:
# Group A
A = np.array([
 [ 2, 1],
 [ 5, 4],
 [ 1, 6],
 [ 7, 2]
]) 
# Group B
B = np.array([
 [0, 0],
 [6, 3],
 [3, 5]
])

print("Shape before reshaping: ",A.shape)
print("Shape before reshaping: ",B.shape)

A_ = A[:, np.newaxis, :]
B_ = B[np.newaxis, :, :]

print("Shape after reshaping: ",A_.shape)
print("Shape after reshaping: ",B_.shape)

dif = A_ - B_
print("Difference:\n" , dif)

sq_dif = dif ** 2;
print("Square difference:\n" , sq_dif)

sum_sq = np.sum(sq_dif, axis=2)
print("Shape of Square difference:\n", sum_sq.shape)
print(sum_sq)

eu_dist = np.sqrt(sum_sq)
print("Euclidean distance: ", eu_dist)

Shape before reshaping:  (4, 2)
Shape before reshaping:  (3, 2)
Shape after reshaping:  (4, 1, 2)
Shape after reshaping:  (1, 3, 2)
Difference:
 [[[ 2  1]
  [-4 -2]
  [-1 -4]]

 [[ 5  4]
  [-1  1]
  [ 2 -1]]

 [[ 1  6]
  [-5  3]
  [-2  1]]

 [[ 7  2]
  [ 1 -1]
  [ 4 -3]]]
Square difference:
 [[[ 4  1]
  [16  4]
  [ 1 16]]

 [[25 16]
  [ 1  1]
  [ 4  1]]

 [[ 1 36]
  [25  9]
  [ 4  1]]

 [[49  4]
  [ 1  1]
  [16  9]]]
Shape of Square difference:
 (4, 3)
[[ 5 20 17]
 [41  2  5]
 [37 34  5]
 [53  2 25]]
Euclidean distance:  [[2.23606798 4.47213595 4.12310563]
 [6.40312424 1.41421356 2.23606798]
 [6.08276253 5.83095189 2.23606798]
 [7.28010989 1.41421356 5.        ]]
